-- Auswertung & Ereignis-Log für die Web-Konsole.

-- ── Ereignis-Log je Box ──────────────────────────────────────────────────────
-- Die Box puffert Ereignisse lokal (offline) und lädt sie per Sync hoch.
create table if not exists public.device_events (
  id        bigint generated by default as identity primary key,
  device_id text references public.devices(id) on delete cascade,
  ts        timestamptz not null default now(),
  level     text not null default 'info',   -- info | warn | error
  type      text not null,                   -- startup | print_error | printer_unreachable | pool_empty | update_* | ...
  message   text,
  data      jsonb not null default '{}'::jsonb
);
create index if not exists device_events_device_ts_idx on public.device_events(device_id, ts desc);

alter table public.device_events enable row level security;
do $$ begin
  create policy "device_events full access" on public.device_events
    for all using (true) with check (true);
exception when duplicate_object then null; end $$;

-- Schneller Zugriff auf print_jobs je Box + Zeit (für die Statistik).
create index if not exists print_jobs_device_created_idx
  on public.print_jobs ((data->>'device_id'), created_at);

-- ── Statistik: Ausgaben je Template & Status im Zeitraum ─────────────────────
create or replace function public.dispense_stats(
  p_device_id text,
  p_from      timestamptz,
  p_to        timestamptz
)
returns table (template text, status text, count bigint)
language sql
stable
as $$
  select coalesce(pj.data->>'template', '?') as template,
         pj.status::text                      as status,
         count(*)                             as count
  from public.print_jobs pj
  where pj.data->>'device_id' = p_device_id
    and pj.created_at >= p_from
    and pj.created_at <  p_to
  group by 1, 2
  order by 1, 2;
$$;
