-- Printable Box Platform – Schema
--
-- Führt das vereinte Konzept auf DB-Ebene ein:
--   devices          – zentrale Box-Konfiguration (Single Source of Truth)
--   device_templates – Template-Mix je Box (Gewichte, Cooldowns, Limits, Reward)
--   voucher_pool     – vorproduzierte Codes je Kategorie (Bestandslimit)
--   reserve_vouchers – atomare Reservierung eines Batches an eine Box
--
-- `templates` und `print_jobs` existieren bereits und werden nur genutzt.

-- ─────────────────────────────────────────────────────────── Enums ──────────
do $$ begin
  create type reward_type as enum ('none', 'static', 'unique');
exception when duplicate_object then null; end $$;

do $$ begin
  create type voucher_status as enum ('available', 'reserved', 'claimed');
exception when duplicate_object then null; end $$;

-- ────────────────────────────────────────────────────────── devices ─────────
create table if not exists public.devices (
  id              text primary key,
  name            text,
  location        text,
  config          jsonb        not null default '{}'::jsonb,
  -- Self-Update: vom Backend gewünschte App-Version (z.B. 'v1.2.0')
  desired_version text,
  -- Telemetrie (von der Box gemeldet)
  app_version     text,
  last_seen       timestamptz,
  voucher_stock   jsonb        not null default '{}'::jsonb,
  created_at      timestamptz  not null default now(),
  updated_at      timestamptz  not null default now()
);

-- ───────────────────────────────────────────────── device_templates ─────────
create table if not exists public.device_templates (
  id               bigint generated by default as identity primary key,
  device_id        text    not null references public.devices(id) on delete cascade,
  template_id      bigint  not null references public.templates(id) on delete cascade,
  enabled          boolean not null default true,
  -- Gewichtete Zufallsauswahl (lokal auf der Box)
  probability      int     not null default 0,
  cooldown_sec     int     not null default 0,
  -- Zusätzliche Template-Daten, z.B. {"price":"25%"}
  data             jsonb   not null default '{}'::jsonb,
  -- Belohnung / Gutschein
  reward_type      reward_type not null default 'none',
  voucher_category text,
  static_code      text,
  -- Tempolimit (lokaler Tageszähler auf der Box)
  daily_limit      int,
  -- Trost-Fallback, wenn nichts anderes verfügbar ist
  is_fallback      boolean not null default false,
  created_at       timestamptz not null default now(),
  unique (device_id, template_id)
);

create index if not exists device_templates_device_idx on public.device_templates(device_id);

-- ────────────────────────────────────────────────────── voucher_pool ────────
create table if not exists public.voucher_pool (
  id          bigint generated by default as identity primary key,
  code        text           not null unique,
  category    text           not null,
  status      voucher_status not null default 'available',
  -- an welche Box reserviert / von welcher eingelöst
  device_id   text references public.devices(id) on delete set null,
  reserved_at timestamptz,
  claimed_at  timestamptz,
  created_at  timestamptz    not null default now()
);

-- Schneller Zugriff auf freie Codes je Kategorie (für die Reservierung).
create index if not exists voucher_pool_available_idx
  on public.voucher_pool(category, created_at)
  where status = 'available';
create index if not exists voucher_pool_device_idx on public.voucher_pool(device_id);

-- ───────────────────────────────────── reserve_vouchers (atomar) ────────────
-- Reserviert bis zu p_limit freie Codes einer Kategorie exklusiv für eine Box.
-- FOR UPDATE SKIP LOCKED verhindert, dass zwei Boxen denselben Code bekommen –
-- so hält das globale Bestandslimit auch bei parallelem Nachschub.
create or replace function public.reserve_vouchers(
  p_device_id text,
  p_category  text,
  p_limit     int
)
returns table (code text)
language plpgsql
as $$
begin
  return query
  with picked as (
    select vp.id
    from public.voucher_pool vp
    where vp.category = p_category
      and vp.status = 'available'
    order by vp.created_at
    limit greatest(p_limit, 0)
    for update skip locked
  )
  update public.voucher_pool vp
  set status = 'reserved',
      device_id = p_device_id,
      reserved_at = now()
  from picked
  where vp.id = picked.id
  returning vp.code;
end;
$$;

-- ───────────────────────────────────────────── updated_at Trigger ───────────
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists devices_touch_updated_at on public.devices;
create trigger devices_touch_updated_at
  before update on public.devices
  for each row execute function public.touch_updated_at();

-- ───────────────────────────────────────────────────────────── RLS ──────────
-- Boxen nutzen den anon/service Key. Die Policies hier sind bewusst einfach
-- gehalten; für den Produktivbetrieb sollten die Box-Keys pro Gerät gescoped
-- und die Policies entsprechend verschärft werden.
alter table public.devices          enable row level security;
alter table public.device_templates enable row level security;
alter table public.voucher_pool      enable row level security;

do $$ begin
  create policy "devices read/write for authenticated"
    on public.devices for all
    using (true) with check (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "device_templates read for all"
    on public.device_templates for select using (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "voucher_pool read for all"
    on public.voucher_pool for select using (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "voucher_pool update for all"
    on public.voucher_pool for update using (true) with check (true);
exception when duplicate_object then null; end $$;
